# Convert Qwen3-4B-Base into a reasoning model via GRPO by using OpenR1's Math dataset

In [1]:
# Python >= 3.10
# pip install unsloth vllm

from unsloth import FastLanguageModel
from datasets import Dataset, load_dataset
from vllm import SamplingParams
from trl import SFTTrainer, SFTConfig, GRPOConfig, GRPOTrainer
from transformers import TextStreamer
import torch
import pandas as pd
import numpy as np
import gc

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 08-21 09:23:03 [__init__.py:241] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!

In [2]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"[INFO] Using {device} device")

[INFO] Using cuda device

## (1) Prepare model

In [3]:
max_seq_length = 2048  # increase for longer reasoning traces
lora_rank = 32         # [8, 16, 32, 64, 128] Larger rank => smarter & slower

In [4]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen3-4B-Base",
    max_seq_length = max_seq_length,
    load_in_4bit = False,  # False for LoRA 16bit
    fast_inference = True, # Enable vLLM fast inference
    max_lora_rank = lora_rank,
    gpu_memory_utilization = 0.7, # Reduce if out of memory
)

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.
WARNING:huggingface_hub._login:Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Unsloth: Patching vLLM v1 graph capture
Unsloth: Patching vLLM v0 graph capture
==((====))==  Unsloth 2025.8.9: Fast Qwen3 patching. Transformers: 4.55.2. vLLM: 0.10.1.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.547 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.9. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/Qwen3-4B-Base with actual GPU utilization = 66.38%
Unsloth: Your GPU has CUDA compute capability 8.9 with VRAM = 15.55 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 160.
Unsloth: vLLM's KV Cache can use up to 3.37 GB. Also swap space = 6 GB.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
INFO 08-21 09:23:09 [utils.py:326] non-default args: {'model': 'unsloth/Qwen3-4B-Base', 'dtype': torch.bfloat16, 'seed': 0, 'max_model_len': 2048, 'enable_prefix_caching': True, 'swap_space': 6, 'gpu_memory_utilization': 0.6638059906567738, 'max_num_batched_tokens': 2048, 'max_num_seqs': 160, 'max_logprobs': 0, 'disable_log_stats': True, 'enable_lora': True, 'max_lora_rank': 32, 'compilation_config': {"level":3,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":null,"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":16,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":null,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":null,"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":null,"local_cache_dir":null}}
INFO 08-21 09:23:15 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
INFO 08-21 09:23:15 [__init__.py:1750] Using max model len 2048
INFO 08-21 09:23:16 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 08-21 09:23:17 [core.py:74] Initializing a V1 LLM engine (v0.10.1) with config: model='unsloth/Qwen3-4B-Base', speculative_config=None, tokenizer='unsloth/Qwen3-4B-Base', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen3-4B-Base, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":16,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":320,"local_cache_dir":null}
INFO 08-21 09:23:17 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 08-21 09:23:17 [topk_topp_sampler.py:61] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 08-21 09:23:17 [gpu_model_runner.py:1953] Starting to load model unsloth/Qwen3-4B-Base...
INFO 08-21 09:23:17 [gpu_model_runner.py:1985] Loading model from scratch...
INFO 08-21 09:23:18 [cuda.py:328] Using Flash Attention backend on V1 engine.
INFO 08-21 09:23:18 [weight_utils.py:296] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]

INFO 08-21 09:23:39 [default_loader.py:262] Loading weights took 20.17 seconds
INFO 08-21 09:23:39 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 08-21 09:23:39 [gpu_model_runner.py:2007] Model loading took 7.6334 GiB and 21.428472 seconds
INFO 08-21 09:23:47 [backends.py:548] Using cache directory: /home/huo/.cache/vllm/torch_compile_cache/9c86beb8af/rank_0_0/backbone for vLLM's torch.compile
INFO 08-21 09:23:47 [backends.py:559] Dynamo bytecode transform time: 7.57 s
INFO 08-21 09:23:53 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 5.123 s
INFO 08-21 09:23:55 [monitor.py:34] torch.compile takes 7.57 s in total
INFO 08-21 09:23:55 [gpu_worker.py:276] Available KV cache memory: 1.91 GiB
INFO 08-21 09:23:56 [kv_cache_utils.py:849] GPU KV cache size: 13,904 tokens
INFO 08-21 09:23:56 [kv_cache_utils.py:853] Maximum concurrency for 2,048 tokens per request: 6.79x
INFO 08-21 09:23:56 [vllm_utils.py:643] Unsloth: Running patched vLLM v1 `capture_model`.

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 43/43 [00:06<00:00,  6.89it/s]

INFO 08-21 09:24:02 [gpu_model_runner.py:2708] Graph capturing finished in 6 secs, took 0.54 GiB
INFO 08-21 09:24:02 [vllm_utils.py:650] Unsloth: Patched vLLM v1 graph capture finished in 6 secs.

INFO 08-21 09:24:02 [core.py:214] init engine (profile, create kv cache, warmup model) took 23.14 seconds
INFO 08-21 09:24:03 [llm.py:298] Supported_tasks: ('generate',)
Unsloth: Just some info: will skip parsing ['pre_feedforward_layernorm', 'post_feedforward_layernorm']
Unsloth: Just some info: will skip parsing ['pre_feedforward_layernorm', 'post_feedforward_layernorm']

In [5]:
# Parameter-Efficient Fine-Tuning (PEFT)
# enable efficient adaptation of large pretrained models to various downstream applications 
# by only fine-tuning a small number of (extra) model parameters instead of all parameters. 
model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank,
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha = lora_rank*2,               # speeds up training
    use_gradient_checkpointing = "unsloth", # Reduces memory usage
    random_state = 4096,
)

Unsloth 2025.8.9 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

## (2) GRPO chat template

In [6]:
reasoning_start = "<start_breaking_down>"
reasoning_end   = "<end_breaking_down>"
solution_start  = "<SOLUTION>"
solution_end    = "</SOLUTION>"

system_prompt = \
f"""You are given a problem.
Think about the problem and provide your working out.
Place it between {reasoning_start} and {reasoning_end}.
Then, provide your solution between {solution_start}{solution_end}"""
system_prompt

'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_breaking_down> and <end_breaking_down>.\nThen, provide your solution between <SOLUTION></SOLUTION>'

In [7]:
chat_template = \
    "{% if messages[0]['role'] == 'system' %}"\
        "{{ messages[0]['content'] + eos_token }}"\
        "{% set loop_messages = messages[1:] %}"\
    "{% else %}"\
        "{{ '{system_prompt}' + eos_token }}"\
        "{% set loop_messages = messages %}"\
    "{% endif %}"\
    "{% for message in loop_messages %}"\
        "{% if message['role'] == 'user' %}"\
            "{{ message['content'] }}"\
        "{% elif message['role'] == 'assistant' %}"\
            "{{ message['content'] + eos_token }}"\
        "{% endif %}"\
    "{% endfor %}"\
    "{% if add_generation_prompt %}{{ '{reasoning_start}' }}"\
    "{% endif %}"

In [8]:
chat_template = chat_template\
    .replace("'{system_prompt}'",   f"'{system_prompt}'")\
    .replace("'{reasoning_start}'", f"'{reasoning_start}'")
tokenizer.chat_template = chat_template

In [9]:
# Example
tokenizer.apply_chat_template([
    {"role" : "user", "content" : "What is 1+1?"},
    {"role" : "assistant", "content" : f"{reasoning_start}I think it's 2.{reasoning_end}{solution_start}2{solution_end}"},
    {"role" : "user", "content" : "What is 2+2?"},
], tokenize = False, add_generation_prompt = True)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_breaking_down> and <end_breaking_down>.\nThen, provide your solution between <SOLUTION></SOLUTION><|endoftext|>What is 1+1?<start_breaking_down>I think it's 2.<end_breaking_down><SOLUTION>2</SOLUTION><|endoftext|>What is 2+2?<start_breaking_down>"

## (3) Dataset for pre fine-tuning

In [10]:
dataset = load_dataset("unsloth/OpenMathReasoning-mini", split = "cot")
dataset = dataset.to_pandas()[
    ["expected_answer", "problem", "generated_solution"]
]

In [11]:
# Keep only the expected_answer is a number
is_number = pd.to_numeric(pd.Series(dataset["expected_answer"]), errors = "coerce").notnull()
dataset = dataset.iloc[np.where(is_number)[0]]

In [12]:
dataset.head()

,expected_answer,problem,generated_solution
0,14,Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$...,"<think>\nOkay, let's see. I need to solve the ..."
6,-2,Find the value of the parameter $a$ for which ...,"<think>\nOkay, so I need to find the value of ..."
9,18,What is the sum of all real numbers $x$ for wh...,"<think>\nOkay, so I need to solve the equation..."
13,2,Evaluate the sum \(\sum_{n=1}^\infty \frac{\ph...,"<think>\nOkay, so I need to evaluate the infin..."
17,30,What is the largest positive integer that divi...,"<think>\nAlright, so I need to find the larges..."

In [13]:
# Adapt the dataset to follow GRPO style formatting:
def format_dataset(x):
    expected_answer = x["expected_answer"]
    problem = x["problem"]
    thoughts = x["generated_solution"]
    thoughts = thoughts.replace("<think>", "").replace("</think>", "")
    thoughts = thoughts.strip()
    
    final_prompt = \
        reasoning_start + thoughts + reasoning_end + \
        solution_start + expected_answer + solution_end
    return [
        {"role" : "system",    "content" : system_prompt},
        {"role" : "user",      "content" : problem},
        {"role" : "assistant", "content" : final_prompt},
    ]

dataset["Messages"] = dataset.apply(format_dataset, axis = 1)

In [14]:
# Test
tokenizer.apply_chat_template(dataset["Messages"][0], tokenize = False)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_breaking_down> and <end_breaking_down>.\nThen, provide your solution between <SOLUTION></SOLUTION><|endoftext|>Given $\\sqrt{x^2+165}-\\sqrt{x^2-52}=7$ and $x$ is positive, find all possible values of $x$.<start_breaking_down>Okay, let's see. I need to solve the equation √(x² + 165) - √(x² - 52) = 7, and find all positive values of x. Hmm, radicals can be tricky, but maybe if I can eliminate the square roots by squaring both sides. Let me try that.\n\nFirst, let me write down the equation again to make sure I have it right:\n\n√(x² + 165) - √(x² - 52) = 7.\n\nOkay, so the idea is to isolate one of the radicals and then square both sides. Let me try moving the second radical to the other side:\n\n√(x² + 165) = 7 + √(x² - 52).\n\nNow, if I square both sides, maybe I can get rid of the square roots. Let's do that:\n\n(√(x² + 165))² = (7 + √(x² - 52))².\n\nSimplifying the left side:\n\nx² + 165 = 49 + 14√(x² - 52) + (√(x² - 52))².\n\nThe right side is expanded using the formula (a + b)² = a² + 2ab + b². So the right side becomes 7² + 2*7*√(x² - 52) + (√(x² - 52))², which is 49 + 14√(x² - 52) + (x² - 52).\n\nSo putting it all together:\n\nx² + 165 = 49 + 14√(x² - 52) + x² - 52.\n\nHmm, let's simplify the right side. The x² terms will cancel out, right? Let's subtract x² from both sides:\n\n165 = 49 + 14√(x² - 52) - 52.\n\nSimplify the constants on the right:\n\n49 - 52 is -3, so:\n\n165 = -3 + 14√(x² - 52).\n\nNow, add 3 to both sides to isolate the radical term:\n\n165 + 3 = 14√(x² - 52).\n\nSo 168 = 14√(x² - 52).\n\nDivide both sides by 14:\n\n168 / 14 = √(x² - 52).\n\n12 = √(x² - 52).\n\nNow, square both sides again to eliminate the square root:\n\n12² = x² - 52.\n\n144 = x² - 52.\n\nAdd 52 to both sides:\n\n144 + 52 = x².\n\n196 = x².\n\nSo x = √196 = 14.\n\nBut wait, since the problem states that x is positive, we only take the positive root. So x = 14.\n\nBut hold on, when dealing with squaring equations, sometimes extraneous solutions can come up. I should check if this solution actually satisfies the original equation.\n\nLet's plug x = 14 back into the original equation:\n\n√(14² + 165) - √(14² - 52) = ?\n\nCalculate each term:\n\n14² is 196.\n\nSo first radical: √(196 + 165) = √361 = 19.\n\nSecond radical: √(196 - 52) = √144 = 12.\n\nSo 19 - 12 = 7, which is exactly the right-hand side. So yes, it checks out.\n\nTherefore, the only solution is x = 14. Since the problem says x is positive, we don't have to consider negative roots. So I think that's the answer.\nTo solve the equation \\(\\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\\) for positive \\(x\\), we proceed as follows:\n\n1. Start with the given equation:\n   \\[\n   \\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\n   \\]\n\n2. Isolate one of the square roots by moving \\(\\sqrt{x^2 - 52}\\) to the right side:\n   \\[\n   \\sqrt{x^2 + 165} = 7 + \\sqrt{x^2 - 52}\n   \\]\n\n3. Square both sides to eliminate the square root on the left:\n   \\[\n   (\\sqrt{x^2 + 165})^2 = (7 + \\sqrt{x^2 - 52})^2\n   \\]\n   Simplifying both sides, we get:\n   \\[\n   x^2 + 165 = 49 + 14\\sqrt{x^2 - 52} + (x^2 - 52)\n   \\]\n\n4. Combine like terms on the right side:\n   \\[\n   x^2 + 165 = x^2 - 52 + 49 + 14\\sqrt{x^2 - 52}\n   \\]\n   Simplifying further:\n   \\[\n   x^2 + 165 = x^2 - 3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n5. Subtract \\(x^2\\) from both sides:\n   \\[\n   165 = -3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n6. Add 3 to both sides to isolate the term with the square root:\n   \\[\n   168 = 14\\sqrt{x^2 - 52}\n   \\]\n\n7. Divide both sides by 14:\n   \\[\n   12 = \\sqrt{x^2 - 52}\n   \\]\n\n8. Square both sides again to eliminate the square root:\n   \\[\n   12^2 = x^2 - 52\n   \\]\n   Simplifying:\n   \\[\n   144 = x^2 - 52\n   \\]\n\n9. Add 52 to both sides to solve for \\(x^2\\):\n   \\[\n   196 = x^2\n   \\]\n\n10. Take the positive square root (since \\(x\\) is positive):\n    \\[\n    x = \\sqrt{196} = 14\n    \\]\n\n11. Verify the solution by substituting \\(x = 14\\) back into the original equation:\n    \\[\n    \\sqrt{14^2 + 165} - \\sqrt{14^2 - 52} = \\sqrt{196 + 165} - \\sqrt{196 - 52} = \\sqrt{361} - \\sqrt{144} = 19 - 12 = 7\n    \\]\n    The solution checks out.\n\nThus, the only positive solution is:\n\\[\n\\boxed{14}\n\\]<end_breaking_down><SOLUTION>14</SOLUTION><|endoftext|>"

In [15]:
# Keep only those with reasonable reasoning traces length
dataset["N"] = dataset["Messages"].apply(lambda x: len(tokenizer.apply_chat_template(x)))
dataset = dataset.loc[dataset["N"] <= max_seq_length/2].copy()
dataset.shape

(58, 5)

In [16]:
# Convert to HF dataset
dataset["text"] = tokenizer.apply_chat_template(dataset["Messages"].values.tolist(), tokenize = False)
dataset = Dataset.from_pandas(dataset)
dataset

Dataset({
    features: ['expected_answer', 'problem', 'generated_solution', 'Messages', 'N', 'text', '__index_level_0__'],
    num_rows: 58
})

## (4) Pre fine-tune the model

In [17]:
# Goal is to make the model following the GRPO formatting
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 1,
        warmup_steps = 5,
        num_train_epochs = 2,
        learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
        logging_steps = 5,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 4096,
        report_to = "none",
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/58 [00:00<?, ? examples/s]

In [18]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 58 | Num Epochs = 2 | Total steps = 116
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 1 x 1) = 1
 "-____-"     Trainable parameters = 66,060,288 of 4,088,528,384 (1.62% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=116, training_loss=0.3520683407269675, metrics={'train_runtime': 46.716, 'train_samples_per_second': 2.483, 'train_steps_per_second': 2.483, 'total_flos': 2339032341190656.0, 'train_loss': 0.3520683407269675})

In [19]:
# Test
dataset[0]["Messages"][:2]

[{'content': 'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_breaking_down> and <end_breaking_down>.\nThen, provide your solution between <SOLUTION></SOLUTION>',
  'role': 'system'},
 {'content': 'Jenifer has 82 cents in pennies and nickels. Her younger brother mistook all her nickels for dimes and counted the total as $1.47. How many pennies does Jenifer have?',
  'role': 'user'}]

In [20]:
text = tokenizer.apply_chat_template(
    dataset[0]["Messages"][:2],   # keep system(0) & user(1) prompt, without assistant prompt(2)
    tokenize = False,
    add_generation_prompt = True, # Must add for generation
)
text

'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_breaking_down> and <end_breaking_down>.\nThen, provide your solution between <SOLUTION></SOLUTION><|endoftext|>Jenifer has 82 cents in pennies and nickels. Her younger brother mistook all her nickels for dimes and counted the total as $1.47. How many pennies does Jenifer have?<start_breaking_down>'

In [21]:
text

'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_breaking_down> and <end_breaking_down>.\nThen, provide your solution between <SOLUTION></SOLUTION><|endoftext|>Jenifer has 82 cents in pennies and nickels. Her younger brother mistook all her nickels for dimes and counted the total as $1.47. How many pennies does Jenifer have?<start_breaking_down>'

In [22]:
_ = model.generate(
    **tokenizer(text, return_tensors = "pt").to("cuda"),
    temperature = 0,
    max_new_tokens = 1024,
    streamer = TextStreamer(tokenizer, skip_prompt = False),
)

You are given a problem.
Think about the problem and provide your working out.
Place it between <start_breaking_down> and <end_breaking_down>.
Then, provide your solution between <SOLUTION></SOLUTION><|endoftext|>Jenifer has 82 cents in pennies and nickels. Her younger brother mistook all her nickels for dimes and counted the total as $1.47. How many pennies does Jenifer have?<start_breaking_down>Okay, let's see. So the problem is about Jenifer who has 82 cents in pennies and nickels. But her younger brother thought all the nickels were dimes and counted the total as $1.47. We need to find out how many pennies Jenifer has. Hmm, let me break this down.

First, I need to set up some equations. Let's denote the number of pennies as P and the number of nickels as N. Since pennies are worth 1 cent each and nickels 5 cents each, the total value Jenifer has is 1*P + 5*N = 82 cents. That's the first equation.

Now, her brother mistook all the nickels for dimes. Dimes are 10 cents each. So he counted the total as $1.47, which is 147 cents. So the equation for his count would be 1*P + 10*N = 147. Wait, that's the second equation.

So now we have two equations:
1) P + 5N = 82
2) P + 10N = 147

I need to solve these two equations to find P. Let me think. If I subtract the first equation from the second, the P terms will cancel out. Let's do that.

( P + 10N ) - ( P + 5N ) = 147 - 82
That simplifies to 5N = 65
So N = 65 / 5 = 13

So there are 13 nickels. Then plugging back into the first equation to find P:
P + 5*13 = 82
P + 65 = 82
P = 82 - 65 = 17

So Jenifer has 17 pennies. Let me check that. 17 pennies are 17 cents, and 13 nickels are 65 cents. Total is 82 cents, which matches the problem statement. And if she had 13 nickels mistaken as dimes, that's 130 cents, plus the 17 pennies, which is 147 cents, which is $1.47. That checks out. So the answer should be 17 pennies.
To solve the problem, we start by setting up two equations based on the given information.

1. The total value of the coins Jenifer has is 82 cents:
   \[
   P + 5N = 82
   \]
   where \(P\) is the number of pennies and \(N\) is the number of nickels.

2. Her younger brother mistook all the nickels for dimes and counted the total as $1.47, which is 147 cents:
   \[
   P + 10N = 147
   \]

We now have the system of equations:
\[
\begin{cases}
P + 5N = 82 \\
P + 10N = 147
\end{cases}
\]

To eliminate \(P\), we subtract the first equation from the second:
\[
(P + 10N) - (P + 5N) = 147 - 82
\]
\[
5N = 65
\]
\[
N = 13
\]

Now that we know \(N = 13\), we substitute this value back into the first equation to find \(P\):
\[
P + 5(13) = 82
\]
\[
P + 65 = 82
\]
\[
P = 17
\]

Thus, Jenifer has \(\boxed{17}\) pennies. To verify, we check the total value:
- 17 pennies = 17 cents
- 13 nickels = 65 cents
- Total = 17 + 65 = 82 cents

And if the nickels were mistaken for dimes:
- 13 dimes = 130 cents
- 17 pennies = 17 cents
- Total = 130 + 17 = 147 cents

Both conditions are satisfied, confirming that the solution is correct. Therefore, the number of pennies Jenifer has is \(\boxed{17}\).<end_breaking_down><SOLUTION>17</SOLUTION><|endoftext|>

In [23]:
# Clean up
del dataset
torch.cuda.empty_cache()
gc.collect()

0

## (5) Dataset

In [24]:
dataset = load_dataset("open-r1/DAPO-Math-17k-Processed", "en", split = "train")
dataset

README.md: 0.00B [00:00, ?B/s]

en/train-00000-of-00001.parquet:   0%|          | 0.00/5.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/14116 [00:00<?, ? examples/s]

Dataset({
    features: ['prompt', 'solution', 'data_source', 'source_prompt', 'ability', 'reward_model', 'extra_info'],
    num_rows: 14116
})

In [25]:
# Test
print(dataset[100]["prompt"])
print(dataset[100]["solution"])

Three 12 cm $\times$ 12 cm squares are each cut into two pieces $A$ and $B$, as shown in the first figure below, by joining the midpoints of two adjacent sides. These six pieces are then attached to a regular hexagon, as shown in the second figure, so as to fold into a polyhedron. What is the volume (in $\text{cm}^3$) of this polyhedron?
864

In [26]:
dataset = dataset.map(lambda x: {
    "prompt" : [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": x["prompt"]},
    ],
    "answer": x["solution"],
})
dataset[88]

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

{'prompt': [{'content': 'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_breaking_down> and <end_breaking_down>.\nThen, provide your solution between <SOLUTION></SOLUTION>',
   'role': 'system'},
  {'content': 'Triangle $ABC$ is right-angled at $A$. The circle with center $A$ and radius $AB$ intersects $BC$ and $AC$ internally at points $D$ and $E$ respectively. Given that $BD = 20$ and $DC = 16$, determine $AC^2$.',
   'role': 'user'}],
 'solution': '936',
 'data_source': 'math_dapo',
 'source_prompt': [{'content': 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.\n\nTriangle $ABC$ is right-angled at $A$. The circle with center $A$ and radius $AB$ intersects $BC$ and $AC$ internally at points $D$ and $E$ respectively. Given that $BD = 20$ and $DC = 16$, determine $AC^2$.\n\nRemember to put your answer on its own line after "Answer:".',
   'role': 'user'}],
 'ability': 'MATH',
 'reward_model': {'ground_truth': '936', 'style': 'rule-lighteval/MATH_v2'},
 'extra_info': {'index': 'd613dfb1-9bf4-4824-90ab-dfc83bccb040'},
 'answer': '936'}

In [36]:
tokenized = dataset.map(
    lambda x: {"tokens" : tokenizer.apply_chat_template(x["prompt"], add_generation_prompt = True, tokenize = True)},
    batched = True,
)
print(tokenizer.decode(tokenized[88]["tokens"]))
tokenized = tokenized.map(lambda x: {"L" : len(x["tokens"])})

import numpy as np
maximum_length = int(np.quantile(tokenized["L"], 0.9))
print("Max Length = ", maximum_length)

# Filter only samples smaller than 90% max length
dataset = dataset.select(np.where(np.array(tokenized["L"]) <= maximum_length)[0])
del tokenized

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

You are given a problem.
Think about the problem and provide your working out.
Place it between <start_breaking_down> and <end_breaking_down>.
Then, provide your solution between <SOLUTION></SOLUTION><|endoftext|>Triangle $ABC$ is right-angled at $A$. The circle with center $A$ and radius $AB$ intersects $BC$ and $AC$ internally at points $D$ and $E$ respectively. Given that $BD = 20$ and $DC = 16$, determine $AC^2$.<start_breaking_down>

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

Max Length =  204

## (6) Reward function

In [28]:
import re

solution_end_regex = r"</SOLUTION>[\s]{0,}" + \
    "(?:" + re.escape(tokenizer.eos_token) + ")?"
match_format = re.compile(
    rf"{reasoning_end}.*?"\
    rf"{solution_start}(.+?){solution_end_regex}"\
    rf"[\s]{{0,}}$",
    flags = re.MULTILINE | re.DOTALL
)
# Grab the final answer
match_format

re.compile(r'<end_breaking_down>.*?<SOLUTION>(.+?)</SOLUTION>[\s]{0,}(?:<\|endoftext\|>)?[\s]{0,}$',
           re.MULTILINE|re.DOTALL|re.UNICODE)

In [29]:
# Text
match_format.findall(
    "Both conditions are satisfied, confirming that the solution is correct. Therefore, the number of pennies Jenifer has is \(\boxed{17}\).<end_breaking_down><SOLUTION>17</SOLUTION><|endoftext|>"
)

<>:2: SyntaxWarning: invalid escape sequence '\('
<>:2: SyntaxWarning: invalid escape sequence '\('
/tmp/ipykernel_3954/2935232894.py:2: SyntaxWarning: invalid escape sequence '\('
  "Both conditions are satisfied, confirming that the solution is correct. Therefore, the number of pennies Jenifer has is \(\boxed{17}\).<end_breaking_down><SOLUTION>17</SOLUTION><|endoftext|>"

['17']

In [34]:
match_numbers = re.compile(
    solution_start + r".*?[\s]{0,}([-]?[\d\.\,]{1,})",
    flags = re.MULTILINE | re.DOTALL
)
print(match_numbers)

re.compile('<SOLUTION>.*?[\\s]{0,}([-]?[\\d\\.\\,]{1,})', re.MULTILINE|re.DOTALL)

In [35]:
print(match_numbers.findall("<SOLUTION>  0.34  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>  123,456  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>  -0.234  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>17</SOLUTION>"))
print(match_numbers.findall("<SOLUTION>The solution is $20</SOLUTION>"))

['0.34']
['123,456']
['-0.234']
['17']
['20']

In [30]:
def match_format_exactly(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        if match_format.search(response) is not None: score += 3.0
        scores.append(score)
    return scores

In [31]:
def match_format_approximately(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Count how many keywords are seen - we penalize if too many!
        # If we see 1, then plus some points!
        # No need to reward "reasoning_start" since we always prepend it!
        score += 0.5 if response.count(reasoning_end)   == 1 else -1.0
        score += 0.5 if response.count(solution_start)  == 1 else -1.0
        score += 0.5 if response.count(solution_end)    == 1 else -1.0
        scores.append(score)
    return scores

In [32]:
def check_answer(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_format.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    for guess, true_answer in zip(extracted_responses, answer):
        score = 0
        if guess is None:
            scores.append(-2.0)
            continue
        # Correct answer gets 5 points!
        if guess == true_answer:
            score += 5.0
        # Match if spaces are seen, but less reward
        elif guess.strip() == true_answer.strip():
            score += 3.5
        else:
            # We also reward it if the answer is close via ratios!
            # Ie if the answer is within some range, reward it!
            try:
                ratio = float(guess) / float(true_answer)
                if   ratio >= 0.9 and ratio <= 1.1: score += 2.0
                elif ratio >= 0.8 and ratio <= 1.2: score += 1.5
                else: score -= 2.5 # Penalize wrong answers
            except:
                score -= 4.5 # Penalize
        scores.append(score)
    return scores

In [38]:
global PRINTED_TIMES
PRINTED_TIMES = 0
global PRINT_EVERY_STEPS
PRINT_EVERY_STEPS = 5

def check_numbers(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_numbers.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    # Print only every few steps
    global PRINTED_TIMES
    global PRINT_EVERY_STEPS
    if PRINTED_TIMES % PRINT_EVERY_STEPS == 0:
        print(
            '*'*20 + f"Question:\n{question}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}"
        )
    PRINTED_TIMES += 1

    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None:
            scores.append(-2.5)
            continue
        # Convert to numbers
        try:
            true_answer = float(true_answer.strip())
            # Remove commas like in 123,456
            guess       = float(guess.strip().replace(",", ""))
            scores.append(3.5 if guess == true_answer else -1.5)
        except:
            scores.append(0)
            continue
    return scores

## (7) GRPO Training

In [44]:
max_prompt_length = maximum_length + 1
max_completion_length = max_seq_length - max_prompt_length

training_args = GRPOConfig(
    vllm_sampling_params = SamplingParams(
        min_p = 0.1,
        top_p = 1.0,
        top_k = -1,
        seed = 4096,
        stop = [tokenizer.eos_token],
        include_stop_str_in_output = True,
    ),
    temperature = 1.0,
    learning_rate = 5e-6,
    weight_decay = 0.01,
    warmup_ratio = 0.1,
    lr_scheduler_type = "linear",
    optim = "adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 4,             # Decrease if out of memory
    max_prompt_length = max_prompt_length,
    max_completion_length = max_completion_length,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 300,
    save_steps = 100,
    report_to = "none",
    output_dir = "outputs",

    # For optional training + evaluation
    # fp16_full_eval = True,
    # per_device_eval_batch_size = 4,
    # eval_accumulation_steps = 1,
    # eval_strategy = "steps",
    # eval_steps = 1,
)

Unsloth: We now expect `per_device_train_batch_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 4

In [45]:
# For optional training + evaluation
# new_dataset = dataset.train_test_split(test_size = 0.01)

trainer = GRPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        match_format_exactly,
        match_format_approximately,
        check_answer,
        check_numbers,
    ],
    args = training_args,
    train_dataset = dataset,

    # For optional training + evaluation
    # train_dataset = new_dataset["train"],
    # eval_dataset = new_dataset["test"],
)

In [46]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 12,709 | Num Epochs = 1 | Total steps = 300
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 66,060,288 of 4,088,528,384 (1.62% trained)

********************Question:
Compute the number of positive integers that divide at least two of the integers in the set $\{1^1,2^2,3^3,4^4,5^5,6^6,7^7,8^8,9^9,10^{10}\}$.
Answer:
22
Response:
Okay, so I need to find how many positive integers divide at least two of the numbers in the set {1^1, 2^2, 3^3, ..., 10^10}. Hmm, let me think. First, I should probably list out all the numbers in the set and then determine their divisors. But wait, some of these numbers are going to have common divisors because their exponents are multiples of each other. For example, 2^2 and 4^4 share common divisors since 4^4 is a power of 2. Let me see.

The set is {1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000}. So, each number is a power of an integer. To find the divisors that divide at least two of these numbers, I need to consider the greatest common divisors (GCDs) between pairs. But actually, since we're looking for divisors that divide at least two numbers, it's equivalent to finding all common divisors of any two numbers in the set, then counting them. But wait, maybe there's a smarter way.

Let me think about the least common multiple (LCM) first. If two numbers have a common divisor, then their LCM will be divisible by their GCD. But perhaps a better approach here is to find the prime factorizations of each number and then see which prime factors are common between pairs.

Let me list the prime factorizations:

- 1: 1 (trivial, can be ignored since 1 divides every number, but we need to divide at least two in the set)
- 2^2: 2^2
- 3^3: 3^3
- 4^4: (2^2)^4 = 2^8
- 5^5: 5^5
- 6^6: (2*3)^6 = 2^6 * 3^6
- 7^7: 7^7
- 8^8: (2^3)^8 = 2^24
- 9^9: (3^2)^9 = 3^18
- 10^10: (2*5)^10 = 2^10 * 5^10

Now, to find divisors that divide at least two numbers, we need to consider the GCD of any two numbers. The GCD is the minimum of the exponents for each prime in their factorizations. So, for example, GCD(2^2, 4^4) = GCD(2^2, 2^8) = 2^2. Similarly, GCD(2^2, 3^3) = 1, since they have no common prime factors. So divisors of these pairs would be the divisors of the GCD.

But we need to find all such common divisors across the entire set. This seems like a lot of work because there are 10 numbers, and the number of pairs is C(10,2) = 45. But maybe instead of checking all pairs, we can look for the common primes first.

Looking at the numbers, the primes involved are 2, 3, 5, 7, 11, etc. But wait, 10^10 has 2 and 5 as its prime factors, but none of the other numbers have 11. So the maximum primes are 2, 3, 5, 7, 11, etc. So for each prime, we need to check if it's present in at least two numbers.

For example, prime 2 is in all the even-numbered terms, so pairs involving even terms will have GCDs that include 2. Similarly, 3 is only in the 3rd, 6th, 9th terms, etc.

Wait, but we need to count the common divisors. So for each pair (a, b), the number of common divisors is equal to the number of divisors of their GCD. So for each pair, we compute their GCD, then the number of divisors of that GCD. Then sum over all pairs, but we have to avoid double-counting since each divisor is counted multiple times.

Alternatively, maybe there's a smarter way. Let me think about the set of all possible greatest common divisors. Since the GCD of two numbers is the product of the minimum powers of each prime in their factorizations, the possible GCDs are those numbers that are products of primes with exponents that are the minimum of the exponents in the two numbers.

But perhaps a better approach is to realize that any common divisor must divide all pairs, but since we're looking for divisors that divide at least two, we need to consider all combinations where at least two numbers share a divisor. This is equivalent to the number of divisors of each number, but wait, that's not right. Maybe inclusion-exclusion?

Wait, perhaps the total number is the sum of the number of divisors of each number divided by 2, minus the cases where divisors are counted more than twice. But this is getting complicated. Maybe I should just list the numbers and find their GCDs pairwise.

Alternatively, since the numbers are of the form p^n where p is prime (except 1), the GCD of two numbers a=p^m and b=q^n (with p not equal to q) is 1. Unless they have the same prime base. So pairs where the numbers share the same prime base will have GCDs that are powers of that prime.

For example, 2^2 and 4^4 have common divisors including 2^2. Similarly, 3^3 and 9^9 have common divisors including 3^3. So for each prime p, the pairs where both numbers are powers of p will have GCDs that are powers of p. The number of such pairs for each prime p is C(k, 2) where k is the number of terms that are powers of p.

Looking at the set, the powers of 2 are 2^2, 4^4, 8^8, 10^10 (since 10 = 2*5, but 10^10 has 2^10). So that's 4 terms. The powers of 3 are 3^3, 6^6, 9^9 (3 terms). Powers of 5: only 5^5 (1 term). Powers of 7: only 7^7 (1 term). Powers of 11: none. So primes 2, 3, 5, 7 contribute to pairs with common divisors.

So for each prime, the number of pairs is C(k,2) where k is the number of its powers in the set. Then for each pair, the number of divisors is the number of divisors of their GCD, which is the power p^min.

But the divisors of p^x are 1, p, p^2, ..., p^x, so x+1 divisors. So for each pair of the same prime, there are (min exponent +1) divisors. Let me compute this.

For prime 2: exponents 2 (2^2), 8 (4^4), 24 (8^8), 10 (10^10). Wait, 10^10 is 2^10*5^10, so the power of 2 here is 10. So the exponents for the powers of 2 are 2, 8, 24, 10. The pairs are (2,8), (2,24), (2,10), (8,24), (8,10), (24,10). Each pair has GCD that's the minimum of their exponents. So for each pair, the number of divisors is the minimum exponent +1.

Compute each: (2,8): min is 2, 3 divisors; (2,24): min 2, 3; (2,10): min 2, 3; (8,24): min 8, 11 divisors; (8,10): min 8, 11; (24,10
Extracted:
None

********************Question:
The sum of $\lfloor x \rfloor$ for all real numbers $x$ satisfying the equation $16 + 15x + 15x^2 = \lfloor x \rfloor^3$ is:
Answer:
33
Response:
Okay, so I need to solve this equation where 16 plus 15x plus 15x squared equals the floor of x cubed. The floor function, denoted with <code>floor(x)</code>, gives the greatest integer less than or equal to x. The problem is asking for the sum of all integer parts of x that satisfy the equation. Hmm, let me break this down step by step.

First, I need to find all real numbers x such that 16 + 15x +15x² equals floor(x)³. Maybe I can start by letting y = floor(x). Since floor(x) is an integer, y is an integer as well. So, the equation becomes 16 + 15x +15x² = y³.

But wait, x is a real number, but when we take its floor, it's the greatest integer less than or equal to x. So, y ≤ x < y+1. Maybe I can substitute x with y plus some decimal part, say x = y + d, where 0 ≤ d <1. But that might make the equation more complicated. Alternatively, perhaps I can consider possible integer values for y and then check if x exists for each y that's a solution.

Let me rearrange the equation to see if I can express x in terms of y. The equation is 15x² +15x +16 = y³. Hmm, that's a quadratic in x. Maybe I can solve for x using the quadratic formula. The quadratic equation is ax² + bx + c = 0, so x = [-b ± √(b² - 4ac)] / (2a). Applying that here:

a is 15, b is 15, c is 16 - y³. So x = [-15 ± √(15² - 4*15*(16 - y³))] / 30. Let's compute the discriminant: (15)² - 4*15*(16 - y³) = 225 - 60*(16 - y³) = 225 - 960 + 60y³ = -735 + 60y³. So the discriminant is 60y³ -735. For real solutions, the discriminant must be non-negative: 60y³ - 735 ≥ 0 ⇒ 60y³ ≥ 735 ⇒ y³ ≥ 735/60 ⇒ y³ ≥ 12.25. So y³ ≥ 12.25, which means y ≥ ∛12.25. Since y is an integer, the smallest possible y is 3 (because 2³ = 8 < 12.25 and 3³ =27 ≥ 12.25). So y can be 3, 4, 5,... on up. But wait, since x < y+1, and x is a real number, maybe for larger y, the equation won't have real solutions.

Let me test y = 3 first. Then the equation is 15x² +15x +16 = 27 => 15x² +15x -11 = 0. Using the quadratic formula: x = [-15 ± √(225 + 660)]/30 = [-15 ± √885]/30. √885 is approximately 29.75, so x ≈ (-15 +29.75)/30 ≈ 14.75/30 ≈ 0.492 and (-15 -29.75)/30 ≈ -44.75/30 ≈ -1.492. So x is approximately 0.492 and -1.492. But since y=3 is floor(x), x must be ≥3. So these solutions are too low. Therefore, y=3 doesn't work.

Next, y=4. Then 15x² +15x +16 =64 ⇒ 15x² +15x -48 = 0. Dividing by 3: 5x² +5x -16 = 0. Solutions: x = [-5 ± √(25 + 320)]/10 = [-5 ± √345]/10. √345 is about 18.57, so x ≈ (-5 +18.57)/10 ≈ 13.57/10 ≈ 1.357 and (-5 -18.57)/10 ≈ -23.57/10 ≈ -2.357. Again, these are less than 4, so y=4 doesn't work.

Next, y=5. Then 15x² +15x +16=125 ⇒ 15x² +15x -109 = 0. Solutions: x = [-15 ± √(225 + 6540)]/30 = [-15 ± √6765]/30. √6765 is about 82.25, so x ≈ (-15 +82.25)/30 ≈ 67.25/30 ≈ 2.242 and (-15 -82.25)/30 ≈ -97.25/30 ≈ -3.242. So here, one of the solutions is around 2.242, which is between 2 and 3, but y=5 requires x≥5. So these solutions don't work. Wait, but maybe there's a solution between y=5 and y=6? Let me check y=6. Then the equation is 15x² +15x +16 =216 ⇒ 15x² +15x -200 = 0. Solved by 15 times x² +15x =200. Dividing by 5: 3x² +3x -40 = 0. Solutions: x = [-3 ± √(9 + 480)]/6 = [-3 ± √489]/6. √489 is about 22.11, so x ≈ (-3 +22.11)/6 ≈ 19.11/6 ≈ 3.185 and (-3 -22.11)/6 ≈ -25.11/6 ≈ -4.185. So here, the possible x values are around 3.185 and -4.185. But y=6 requires x≥6. So x≈3.185 is less than 6, so y=6 doesn't work. Therefore, y=6 is too big.

Wait, maybe I made a mistake. Let me double-check. For y=5, the equation was 15x² +15x -109 = 0. The discriminant is 225 +6360=6585. √6585 is about 81.15. So x ≈ (-15 +81.15)/30 ≈ 66.15/30 ≈ 2.205 and (-15 -81.15)/30 ≈ -96.15/30 ≈ -3.205. These are both less than 5, so no solutions here. Then y=4 gave solutions around 1.357 and -2.357, which are less than 4, so y=4 doesn't work. y=3 gave solutions around 0.492 and -1.492, which are less than 3. So no solutions for y≤3. Then y=6 gave solutions around 3.185 and -4.185, but y=6 requires x≥6, so y=6 doesn't work. Then y=7. The equation becomes 15x² +15x +16=343 ⇒ 15x² +15
Extracted:
None
********************Question:
Letters $A, B, C,$ and $D$ represent four different digits from 0, 1, 2, 3, ..., 9. If $\frac{A+B}{C+D}$ is an integer that is as large as possible, what is the value of $A+B$?
Answer:
17
Response:
Okay, so I need to solve this problem where letters A, B, C, and D represent four different digits from 0 to 9. The fraction (A + B)/(C + D) needs to be as large as possible, and I have to find the value of A + B when that happens. Hmm, let's see.

First, since the fraction needs to be as large as possible, that means the numerator (A + B) should be as large as possible, and the denominator (C + D) should be as small as possible. But wait, they have to be different digits, right? So A, B, C, D are all distinct digits from 0 to 9.

Okay, so to maximize (A + B)/(C + D), the trick here is to make the numerator as big as possible and the denominator as small as possible. Let's think about the maximum possible sum for A + B. Since A and B are different digits (because all four digits are different), the largest possible values for A and B would be 9 and 8, right? Because if one is 9, the other can't be 9, so the next highest is 8. So 9 + 8 = 17. So A + B would be at most 17.

But then, the denominator needs to be as small as possible. The smallest possible sum for C + D, with all digits being different and including 9 and 8 in the numerator, would be the next lowest digits. Since 9 and 8 are already used in the numerator, the smallest digits available for C and D would be 0 and 1. So 0 + 1 = 1. So the fraction would be 17/1, which is 17. But wait, does that work? Let me check if all digits are different. If A=9, B=8, then C=0, D=1. Yeah, all digits are different: 9, 8, 0, 1. That's valid. So 17/1 = 17. So that's the maximum possible integer value. Therefore, A + B would be 17.

But hold on, let me double-check if there's any other combination where the numerator can be larger than 17 or the denominator smaller than 1. If I try to increase A + B beyond 17, then both A and B would have to be larger, but since the maximum digits are 9 and 8, that's the max. So 9 and 8 sum to 17. If I use 9 and 7, that's 16, which is less than 17. So the numerator can't be higher. Similarly, if I have A + B = 17, and the denominator needs to be as small as possible. The smallest possible denominator would be 1, achieved by C=0 and D=1. Higher than that, like C=1, D=2, would be 3, which would make the fraction smaller. So 17 should be the maximum.

So the answer should be 17. Let me just make sure there isn't another way to arrange the digits to get a larger fraction. What if I use 8 and 9 for the numerator but arrange the denominator differently? Like C=2, D=3, then 17/5=3.4, which is less than 17. If C=1, D=0, then 17/1. So 17/1 is definitely larger. If I try A=7, B=9, then 16, which is less. So no, the maximum is when A=9, B=8. Therefore, A+B is 17.

Therefore, the answer should be 17. Let me just verify once more. If I have A=9, B=8, then the remaining digits are 0 and 1. So C+D=1. Then 9+8/1 = 17, which is an integer. So yes, that's the maximum. Therefore, the value of A+B is 17. So the answer is \boxed{17}.
To solve the problem, we need to maximize the fraction \(\frac{A+B}{C+D}\) where \(A, B, C,\) and \(D\) are distinct digits from 0 to 9.

1. **Maximize the Numerator \(A + B\):**
   - The largest possible values for \(A\) and \(B\) are 9 and 8, respectively.
   - Therefore, \(A + B = 9 + 8 = 17\).

2. **Minimize the Denominator \(C + D\):**
   - The smallest possible values for \(C\) and \(D\) are 0 and 1, respectively.
   - Therefore, \(C + D = 0 + 1 = 1\).

3. **Verify the Values:**
   - With \(A = 9\), \(B = 8\), \(C = 0\), and \(D = 1\), all digits are distinct.
   - The fraction \(\frac{A+B}{C+D} = \frac{17}{1} = 17\), which is an integer.

Thus, the value of \(A + B\) that maximizes the fraction is \(\boxed{17}\).<end_breaking_down><SOLUTION>17</SOLUTION>
Extracted:
17
********************Question:
Let $f(x)=\int_0^{x} e^{t} (\cos t+\sin t)\, dt$, $g(x)=\int_0^{x} e^{t} (\cos t-\sin t)\, dt$.

For a real number $a$, find:
\[ \sum_{n=1}^{\infty} \frac{e^{2a}}{\{f^{(n)}(a)\}^2+\{g^{(n)}(a)\}^2}. \]
Answer:
1
Response:
Okay, let's see here. I've got this problem involving functions f and g defined by integrals, and I need to find the sum of an infinite series where each term is e^(2a) divided by the sum of the squares of the nth derivatives of f and g evaluated at a. Hmm, derivatives? Integrals? L'Hôpital's Rule? Taylor series? Let me try to break this down step by step.

First, the functions f and g are given by integrals from 0 to x of e^t times either (cos t + sin t) and (cos t - sin t), respectively. So, f(x) = integral [ e^t (cos t + sin t) dt from 0 to x ]. Similarly, g(x) is the same integral but with cos t - sin t.

But then, how do these functions help in finding their nth derivatives, f^(n)(a) and g^(n)(a)? Maybe I should consider differentiating the integrand? Wait, the integrals are from 0 to x, so when I differentiate f with respect to x, by the Leibniz rule, the derivative should just be the integrand evaluated at x, right? So f'(x) = e^x (cos x + sin x), and similarly, g'(x) = e^x (cos x - sin x).

But then, the problem is asking for the sum of the series where each term is e^(2a) divided by (f^(n)(a))^2 + (g^(n)(a))^2. Since f and g are exponential functions multiplied by trigonometric functions, their derivatives might have a pattern. Let me calculate the first few derivatives to see if there's a cycle.

Let's start with f. The first derivative is f'(x) = e^x (cos x + sin x). Then f''(x) would be the derivative of that. So using the product rule, it's e^x*(cos x + sin x) + (cos x + sin x)*e^x = 2e^x (sin x + cos x). Wait, hold on. Let me check that again.

Right, derivative of e^x (cos x + sin x) is e^x*(cos x + sin x) + e^x*(-sin x + cos x) = e^x (cos x + sin x - sin x + cos x) = 2e^x cos x. Wait, that's different. I think I made a mistake earlier. Let me redo f' first. f'(x) = e^x cos x + e^x sin x. Then f''(x) = e^x cos x + e^x (-sin x) + e^x sin x + e^x cos x = 2e^x cos x. So perhaps the derivatives alternate between e^x (something) and 2e^x (something).

Let me compute f'''(x). That would be 2e^x cos x - 2e^x sin x = 2e^x (cos x - sin x). So f''' = g'. Then f''''(x) = 2e^x (-sin x - cos x) = -2e^x (sin x + cos x) = -2f'. So f'''' = -2f. So the derivatives of f cycle every 4 terms: f, f', 2f', 2f, -2f, -2f', -f', -f, etc. So the pattern repeats every 8 derivatives.

Similarly, maybe g behaves similarly. Let me compute the first derivatives of g. g'(x) = e^x (cos x - sin x). Then g''(x) = e^x (cos x - sin x) + e^x (-sin x - cos x) = e^x (cos x - sin x - sin x - cos x) = -2e^x sin x. Then g'''(x) = -2e^x cos x. Then g''''(x) = -2e^x (-sin x) = 2e^x sin x = 2g'. Then g'''''(x) = 2e^x cos x. Then g''''''(x) = 2g''. So g's derivatives follow a pattern like 2g', -4g', 2g'', -4g'', 2g, -4g, etc. Hmm, this seems a bit complicated. Maybe I should look for a pattern in a different way.

Wait, perhaps instead of computing each derivative, there's a closed-form expression for f^(n)(x) and g^(n)(x). Notice that e^x (cos x + sin x) can be written as √2 e^x cos(x - π/4), since cos θ + sin θ = √2 cos(θ - π/4). Similarly, e^x (cos x - sin x) = √2 e^x sin(x - π/4). So maybe using Euler's formula could help.

Wait, e^(a+ib) = e^a (cos b + i sin b). Here, e^x (cos x + sin x) = √2 e^x cos(x - π/4). So perhaps each derivative follows a pattern where the coefficients cycle every 4 terms due to the cosine function's periodic derivatives (first derivative changes sign, and after that, the amplitudes scale).

So, for f, the derivatives might be (f, f', 2f', 2f, -2f, -2f', -f', -f, ...). Then f^(4k) = 2^k f, f^(4k+1) = 2^k f', f^(4k+2) = 2^(k+1) f', f^(4k+3) = -2^(k+1) f, and then it cycles. Similarly for g.

But then, at x = a, each derivative evaluated at a could be expressed in terms of e^a and trigonometric functions of a. Then, the sum in the problem would be e^(2a) divided by the sum of squares of these derivatives. So for each n, compute the nth derivative, multiply by itself, sum all those, then divide by e^(2a) and take the reciprocal. Then sum over all n.

But since the derivatives cycle every 8 terms (from f to -f), maybe the sum telescopes or simplifies. Wait, let me think about the nth derivative's value at a. Let's say a = 0 for simplicity, check. Then f(0) = 1, f'(0) = 1, f''(0) = 2, f'''(0) = 2, f''''(0) = -2, etc. Then f^(2) = 2, f^4 = 2, f^6 = -2, f^8 = -2, etc. Wait, at x=0, f^(n)(0) alternates between 2 and -2 every two steps. So the sum would be (2^2 + 1^2)/(2^2 +1^2) + (2^2 +1^2)/(2^2 +4) + (4^2 +1)/(4^2 +16) + ... Wait, plugging in n=1,2,3,... at x=0.

Wait, perhaps the ratio (2^2 +1^2)/(2^2 +1^2) is 5/5=1, n=2: (4+1)/(4+16) = 5/20=1/4, n=3: (4+1)/(16+1)=5/17, etc. Wait, that's not a geometric series. Hmm. Maybe I'm doing something wrong. Wait, perhaps I should compute the first few derivatives to find a pattern.

Let me write out the derivatives of f and g more carefully. Let f(x) = ∫e^t (cos t + sin t) dt, so f'(x) = e^x (cos x + sin x). Then f''(x) = e^x (cos x - sin x) + e^x (-sin x + cos x) = 2e^x cos x. Wait, no: f'(x) = e^x cos x + e^x sin x. Then f''(x) = e^x cos x - e^x sin x + e^
Extracted:
None
********************Question:
How many distinct ordered pairs of positive integers $(m,n)$ are there so that the sum of the reciprocals of $m$ and $n$ is $\frac14$?
Answer:
5
Response:
Okay, so I need to find the number of distinct ordered pairs of positive integers (m, n) such that the sum of their reciprocals is 1/4. Hmm, let's break this down. The equation is 1/m + 1/n = 1/4. I need to find all positive integer solutions (m, n) where m and n are different.

First, maybe I can rewrite the equation to make it easier to handle. Let's find a common denominator. The equation is (n + m)/mn = 1/4. Cross-multiplying gives 4(m + n) = mn. Let me rearrange that. Bringing all terms to one side, mn - 4m - 4n = 0. Hmm, that's a bit messy. Maybe I can factor this.

Wait, perhaps I can add 16 to both sides to make it factorable. Let's see: mn - 4m - 4n + 16 = 16. Then (m - 4)(n - 4) = 16. Yeah, that seems like a good trick! Adding a constant to both sides allows factoring. Because then (m-4) times (n-4) equals 16. So now, I need to find all pairs of positive integers (a, b) where a * b = 16, and then set m = a + 4 and n = b + 4. Since m and n are integers greater than 4 (because a and b are at least 1), this should work.

Now, the factors of 16 are (1,16), (2,8), (4,4), (8,2), and (16,1). Wait, but since m and n are interchangeable (as the equation is symmetric in m and n), but we need distinct ordered pairs. So each pair (a, b) corresponds to a unique (m, n) pair, except when a = b, which would give the same m and n. So unless a = b, which happens in the case (4,4), the other pairs will give different m and n.

So the factor pairs are (1,16), (2,8), (4,4), (8,2), (16,1). But only the non-symmetric pairs will give distinct (m, n). So the pairs (1,16) and (16,1) correspond to (5,20) and (20,5), respectively. Similarly, (2,8) and (8,2) correspond to (6,12) and (12,6). The pair (4,4) gives (8,8). So all these pairs are distinct.

Counting them: (1,16) gives 2 pairs, (2,8) gives 2 pairs, (4,4) gives 1 pair. Total is 5 pairs. Wait, let me check again. The factor pairs are 5 in total, but since each pair (a,b) and (b,a) are distinct unless a=b, and here a can be less than or greater than b. So yes, each of the three pairs where a ≠ b gives two different ordered pairs, and the middle pair where a=b gives only one. So 3 pairs where a≠b, each contributing 2 pairs, and 1 pair contributing 1 pair. So total is 3*2 +1 =7. But wait, let's list them:

(1,16): (5,20) and (20,5)
(2,8): (6,12) and (12,6)
(4,4): (8,8)
So that's 2+2+1=5. Wait, but earlier I thought 5, but now listing, it's 5. So the answer should be 5. Let me check again. The distinct pairs are (5,20), (20,5), (6,12), (12,6), and (8,8). So that's 5. Therefore, the number of distinct ordered pairs is 5. Let me verify once more. The equation is (m-4)(n-4)=16. The number of solutions is the number of factor pairs of 16, which is 5. Each pair (d, 16/d) gives (m,n)=(d+4, 16/d +4). Since 16 has 5 factors (1,2,4,8,16), hence 5 pairs. Therefore, the answer should be 5.
To solve the problem of finding the number of distinct ordered pairs of positive integers \((m, n)\) such that the sum of the reciprocals of \(m\) and \(n\) is \(\frac{1}{4}\), we start with the equation:

\[
\frac{1}{m} + \frac{1}{n} = \frac{1}{4}
\]

First, we rewrite this equation with a common denominator:

\[
\frac{n + m}{mn} = \frac{1}{4}
\]

Cross-multiplying gives:

\[
4(m + n) = mn
\]

Rearranging terms, we get:

\[
mn - 4m - 4n = 0
\]

To factor this equation, we add 16 to both sides:

\[
mn - 4m - 4n + 16 = 16
\]

This can be factored as:

\[
(m - 4)(n - 4) = 16
\]

Next, we find all pairs of positive integers \((a, b)\) such that \(a \cdot b = 16\). The factor pairs of 16 are:

\[
(1, 16), (2, 8), (4, 4), (8, 2), (16, 1)
\]

For each pair \((a, b)\), we set \(m = a + 4\) and \(n = b + 4\). This gives us the following pairs \((m, n)\):

1. For \((1, 16)\), we get \((1+4, 16+4) = (5, 20)\) and \((20, 5)\)
2. For \((2, 8)\), we get \((2+4, 8+4) = (6, 12)\) and \((12, 6)\)
3. For \((4, 4)\), we get \((4+4, 4+4) = (8, 8)\)

Thus, the distinct ordered pairs \((m, n)\) are:

\[
(5, 20), (20, 5), (6, 12), (12, 6), (8, 8)
\]

Counting these pairs, we see there are 5 distinct ordered pairs. Therefore, the number of distinct ordered pairs \((m, n)\) is:

\[
\boxed{5}
\]<end_breaking_down><SOLUTION>5</SOLUTION>
Extracted:
5
********************Question:
Suppose that $n$ persons meet in a meeting, and that each of the persons is acquainted with exactly $8$ others. Any two acquainted persons have exactly $4$ common acquaintances, and any two non-acquainted persons have exactly $2$ common acquaintances. Find all possible values of $n$.
Answer:
21
Response:
Okay, so I need to find all possible values of n in a problem about people meeting and their acquaintances. Let me try to understand the problem first.

The problem states that there are n people at a meeting, and each person knows exactly 8 others. Then, any two people who know each other have exactly 4 common acquaintances, and any two people who don't know each other have exactly 2 common acquaintances. I need to find all possible values of n.

Hmm, this sounds like a graph theory problem. If I model each person as a vertex in a graph, then each vertex has a degree of 8 because each person knows 8 others. The conditions about common acquaintances might translate to properties of the graph, like the adjacency matrix or something related to graph products.

Wait, the condition that two people who know each other have exactly 4 common acquaintances. That reminds me of the concept of a strongly regular graph. In a strongly regular graph, every vertex has the same number of neighbors (which is 8 here), and any two adjacent vertices have the same number of common neighbors (4 in this case), and any two non-adjacent vertices have the same number of common neighbors (2 here). So maybe this is a strongly regular graph?

Yes, that seems right. Let me recall the definition. A strongly regular graph is defined by three parameters: (k, r, λ, μ), where k is the degree of each vertex, r is the number of common neighbors for two adjacent vertices, and μ is the number of common neighbors for two non-adjacent vertices. So in this problem, k = 8, r = 4, and μ = 2.


TrainOutput(global_step=300, training_loss=0.00015503168057572718, metrics={'train_runtime': 10722.4238, 'train_samples_per_second': 0.112, 'train_steps_per_second': 0.028, 'total_flos': 0.0, 'train_loss': 0.00015503168057572718})

In [47]:
model.save_lora("Qwen3_4B_grpo_lora")

In [51]:
from safetensors import safe_open

tensors = {}
with safe_open("Qwen3_4B_grpo_lora/adapter_model.safetensors", framework = "pt") as f:
    # Verify both A and B are non zero
    for key in f.keys():
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

In [48]:
model_name = "Qwen3-4B-Reasoning"
lora_name = "Qwen3-4B-Reasoning-LoRA"

In [49]:
model.save_pretrained_merged(model_name, tokenizer, save_method = "merged_16bit",)

Found HuggingFace hub cache directory: /home/huo/.cache/huggingface/hub
Checking cache directory for required files...
Successfully copied all 2 files from cache to Qwen3-4B-Reasoning.
Downloading safetensors index for unsloth/Qwen3-4B-Base...

Unsloth: Merging weights into 16bit: 100%|██████████| 2/2 [00:23<00:00, 11.82s/it]

In [68]:
model.save_pretrained(lora_name) 
tokenizer.save_pretrained(lora_name)

('Qwen3-4B-Reasoning-LoRA/tokenizer_config.json',
 'Qwen3-4B-Reasoning-LoRA/special_tokens_map.json',
 'Qwen3-4B-Reasoning-LoRA/chat_template.jinja',
 'Qwen3-4B-Reasoning-LoRA/vocab.json',
 'Qwen3-4B-Reasoning-LoRA/merges.txt',
 'Qwen3-4B-Reasoning-LoRA/added_tokens.json',
 'Qwen3-4B-Reasoning-LoRA/tokenizer.json')

## (8) Inference

In [64]:
# text = "Given two number 9.9 and 9.11, which one is bigger ?"
text = "What is the sqrt of 101?"

In [65]:
# Inference without GRPO
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 1024,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

" - Answers\nMath and Arithmetic\nWhat is the sqrt of 101?\nWiki User\n∙ 2011-03-10 20:04:29\nStudy now\nSee Answer\nBest Answer\nCopy\n10.050378\nWiki User\n∙ 2011-03-10 20:04:29\nThis answer is:\n👍\n🙏\n0\n🤨\n0\n😮\n0\nAdd a Comment\nStudy guides\nAlgebra\n20 cards\nA polynomial of degree zero is a constant term\nThe grouping method of factoring can still be used when only some of the terms share a common factor A True B False\nThe sum or difference of p and q is the of the x-term in the trinomial\nA number a power of a variable or a product of the two is a monomial while a polynomial is the of monomials\n➡️\nSee all cards\nStudy now\nJ's study guide\n1 card\nWhat is the name of Steve on minecraft's name\n➡️\nSee all cards\nStudy now\nSteel Tip Darts Out Chart\n96 cards\n170\n169\n168\n167\n➡️\nSee all cards\nStudy now\nAdd your answer:\nEarn +20 pts\nQ: What is the sqrt of 101?\nSubmit\nWhat is the SQRT of 73?\nThe sqrt of 73 is about 8.54400374531834\nHow do you solve sqrt of 369?\nsqrt(369) = 19.2093727123\nHow to solve the SQRT of 940?\nsqrt(940) = 30.659635051028712\nWhat is the SQRT of 128?\nsqrt(128) = 11.313708498984761\nWhat is the SQRT of 30?\nsqrt(30) = 5.477225575051661\nWhat is the SQRT of 309?\nsqrt(309) = 17.57834637121016\nWhat is the SQRT of 324?\nsqrt(324) = 18\nWhat is the SQRT of -16?\nsqrt(-16) = 4i\nWhat is the SQRT of 81/64?\nsqrt(81/64) = 9/8\nWhat is the SQRT of 5?\nsqrt(5) = 2.23606797749979\nWhat is the SQRT of pi?\nsqrt(pi) = 1.77245385091\nWhat is the SQRT of 2?\nsqrt(2) = 1.41421356237\nWhat is the SQRT of 600?\nsqrt(600) = 24.4948974278\nWhat is the SQRT of 161?\nsqrt(161) = 12.6881344576\nWhat is the SQRT of 450?\nsqrt(450) = 21.2132034356\nWhat is the SQRT of 102?\nsqrt(102) = 10.0995049408\nWhat is the SQRT of 22?\nsqrt(22) = 4.69041575982\nWhat is the SQRT of 441?\nsqrt(441) = 21\nWhat is the SQRT of 125?\nsqrt(125) = 11.1803398875\nWhat is the SQRT of 1?\nsqrt(1) = 1\nWhat is the SQRT of 103?\nsqrt(103) = 10.1488915651\nWhat is the SQRT of 9.9?\nsqrt(9.9) = 3.14642649575\nWhat is the SQRT of 12?\nsqrt(12) = 3.46410161514\nWhat is the SQRT of 2401?\nsqrt(2"

In [71]:
# Inference with GRPO
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user",   "content": "What is the sqrt of 101?"},
#    {"role": "user",   "content": "Given two number 9.9 and 9.11, which one is bigger ?"},
]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False,
)

sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 2048,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("Qwen3_4B_grpo_lora"),
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

"Okay, so I need to find the square root of 101. Hmm, let me think. I know that the square root of 100 is 10, so maybe the square root of 101 is a little more than 10. But how much more? Let me try to estimate.\n\nFirst, I'll see if 101 is a perfect square. Let me check 10^2, which is 100, and 11^2 is 121. So 101 is between 100 and 121. That means the square root of 101 is between 10 and 11. Let's say it's around 10.05 or something? But I need a more accurate value.\n\nMaybe I can use the method of averaging. Let's start with 10 and 11 as the initial bounds. The average of 10 and 11 is 10.5. Let's square that: 10.5 squared is (10 + 0.5)^2 = 100 + 10*1 + 0.25 = 100 + 10 + 0.25 = 110.25. That's higher than 101, so the square root must be less than 10.5. So now I'll average 10 and 10.5, which is 10.25. Squaring 10.25: (10 + 0.25)^2 = 100 + 5 + 0.0625 = 105.0625. Still higher than 101. So next, average 10 and 10.25, which is 10.125. Squaring 10.125: (10 + 0.125)^2 = 100 + 2.5 + 0.015625 = 102.515625. Closer to 101. Let's try 10.1: 10.1 squared is 102.01, which is a bit higher. So the square root is between 10.05 and 10.1. Let's try 10.06: 10.06 squared is 101.2036, which is higher. So the square root is between 10.05 and 10.06. Let's try 10.055: 10.055 squared is 101.103025. Still a bit higher. 10.05? 10.05 squared is 101.0025. That's very close to 101. So the square root of 101 is approximately 10.05.\n\nWait, but maybe there's a more precise way. I remember that for numbers close to a perfect square, like 101 which is 100 plus 1, the square root can be approximated using the formula (a + b)/2 where a is the square root of the perfect square and b is the difference. So (10 + 1)/2 = 5.5. But wait, that doesn't seem right. Hmm, perhaps the formula is something like (a + b/a)/2. Let me check.\n\nFor example, to find the square root of 101, where 100 is 10^2 and 1 is the difference: (10 + 1/10)/2 = (10 + 0.1)/2 = 10.05. Yeah, that gives 10.05. Let me verify 10.05 squared: 100 + 2*10*0.05 + 0.0025 = 100 + 1 + 0.0025 = 101.0025. So that's indeed very close to 101. Therefore, the square root of 101 is approximately 10.05. So the answer should be around 10.1. Let me confirm with a calculator. Wait, the square root of 101 is approximately 10.0498756. So 10.05 is a good approximation. Therefore, the square root of 101 is \\boxed{10.05}<end_breaking_down><SOLUTION>10.05</SOLUTION>"

## (9) Push to HF

In [60]:
hf_model_name = "ZhengjunHUO/Qwen3-4B-Reasoning"   
hf_lora_name = "ZhengjunHUO/Qwen3-4B-Reasoning-LoRA"

In [61]:
hf_token = "hf_foobar"

In [62]:
model.push_to_hub_merged(hf_model_name, tokenizer, save_method = "merged_16bit", token = hf_token)

  0%|          | 0/1 [00:00<?, ?it/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

Found HuggingFace hub cache directory: /home/huo/.cache/huggingface/hub
Checking cache directory for required files...
Successfully copied all 2 files from cache to ZhengjunHUO/Qwen3-4B-Reasoning.
Downloading safetensors index for unsloth/Qwen3-4B-Base...

Unsloth: Merging weights into 16bit:   0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Unsloth: Merging weights into 16bit:  50%|█████     | 1/2 [02:42<02:42, 162.09s/it]

  0%|          | 0/1 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.08G [00:00<?, ?B/s]

Unsloth: Merging weights into 16bit: 100%|██████████| 2/2 [04:03<00:00, 121.95s/it]

In [69]:
model.push_to_hub(hf_lora_name, token = hf_token)

README.md:   0%|          | 0.00/566 [00:00<?, ?B/s]

  0%|          | 0/1 [00:00<?, ?it/s]

adapter_model.safetensors:   0%|          | 0.00/264M [00:00<?, ?B/s]

Saved model to https://huggingface.co/Qwen3-4B-Reasoning-LoRA

In [70]:
tokenizer.push_to_hub(hf_lora_name, token = hf_token)

  0%|          | 0/1 [00:00<?, ?it/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]